---
- name: test new module
  hosts: localhost
  tasks:
  - name: run the thing
    hashicorp_db:
      env: "{{ env }}"
      colo: "{{ colo }}"
      short_code: "{{ short_code }}"
      vault_user: "{{ user }}"
      vault_plugin: "mysql-aurora-database-plugin"
      vault_user_pass: "{{ pass }}"
      database_host: "{{ dbhost }}"
      api_url: "{{ api }}"
    register: testout
  - name: show info
    debug:
      msg: '{{ testout }}'
